/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interficie;

import Dominio.ControladoraDominio;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marc.mauri.ruiz
 */
public class Menu_AdminAlgo extends javax.swing.JFrame {
    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    ControladoraInterficie CD = new ControladoraInterficie();
    /**
     * Creates new form Menu_AdminAlgo
     */
    public Menu_AdminAlgo() {
        initComponents();
    }
    
    public Menu_AdminAlgo(ControladoraInterficie cd) {
        initComponents();
        CD = cd;
    }
    
    public void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,
                "¿Desea salir de la aplicación? Todos los cambios no guardados se perderán.",
                "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,
                null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cliqueP = new javax.swing.JButton();
        girvanN = new javax.swing.JButton();
        louvain = new javax.swing.JButton();
        mostrarConj = new javax.swing.JButton();
        cargarConj = new javax.swing.JButton();
        guardarConj = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        analisis_rendimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("YOUTUBE Mix: Administrar Algoritmos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar Algoritmos");

        cliqueP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cliqueP.setText("Usar Clique Percolation");
        cliqueP.setActionCommand("cliqueP");
        cliqueP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliquePActionPerformed(evt);
            }
        });

        girvanN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        girvanN.setText("Usar Girvan-Newman");
        girvanN.setActionCommand("girvanN");
        girvanN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girvanNActionPerformed(evt);
            }
        });

        louvain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        louvain.setText("Usar Louvain");
        louvain.setActionCommand("louvain");
        louvain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                louvainActionPerformed(evt);
            }
        });

        mostrarConj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mostrarConj.setText("Mostrar conjuntos calculados");
        mostrarConj.setActionCommand("mostrarConj");
        mostrarConj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarConjActionPerformed(evt);
            }
        });

        cargarConj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cargarConj.setText("Cargar conjuntos calculados");
        cargarConj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarConjActionPerformed(evt);
            }
        });

        guardarConj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardarConj.setText("Guardar conjuntos calculados");
        guardarConj.setActionCommand("guardarConj");
        guardarConj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarConjActionPerformed(evt);
            }
        });

        volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        volver.setText("Volver");
        volver.setActionCommand("volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        analisis_rendimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        analisis_rendimiento.setText("Análisis de rendimiento");
        analisis_rendimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analisis_rendimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardarConj, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cliqueP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(girvanN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(louvain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mostrarConj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(analisis_rendimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cargarConj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cliqueP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(girvanN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(louvain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarConj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(analisis_rendimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargarConj, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarConj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarConjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarConjActionPerformed
        if (seleccionado.showDialog(this,"Guardar archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            String path = archivo.getAbsolutePath();
            
            if(archivo.getName().endsWith("txt")) {  //COMPROBAMOS QUE SEA EXTENSION .TXT
                
                if (!archivo.exists()) {    // SI EL FICHERO NO EXISTE LO CREAMOS
                    File fichero = new File(path);
                    try {
                        fichero.createNewFile();
                    } catch (IOException ex) {
                        Logger.getLogger(Menu_AdminAlgo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                if (archivo.canRead()) {    // SI NO PUEDE LEERSE ALGO PASA, ABORTAMOS
                    CD.GuardarConjTab(path);
                    JOptionPane.showMessageDialog(null, "Fichero guardado en \""+ path +"\"");
                }
                else JOptionPane.showMessageDialog(null, "El archivo NO ha podido leerse.");
            }
            else JOptionPane.showMessageDialog(null, "El archivo seleccionado no es un \".txt\" valido.");
        }
    }//GEN-LAST:event_guardarConjActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        MenuPrincipal obj = new MenuPrincipal(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void girvanNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girvanNActionPerformed
        UsarGirvanN obj = new UsarGirvanN(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_girvanNActionPerformed

    private void louvainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_louvainActionPerformed
        UsarLouvain obj = new UsarLouvain(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_louvainActionPerformed

    private void cliquePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliquePActionPerformed
        UsarCliqueP obj = new UsarCliqueP(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_cliquePActionPerformed

    private void mostrarConjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarConjActionPerformed
        MostrarConjuntos obj = new MostrarConjuntos(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_mostrarConjActionPerformed

    private void cargarConjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarConjActionPerformed
        //CargarConjuntos obj = new CargarConjuntos();
        //obj.setVisible(true);
        //obj.setLocationRelativeTo(null);
        if (seleccionado.showDialog(this,"Abrir archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            if (archivo.canRead()) {
                if(archivo.getName().endsWith("txt")) {
                    String filename = archivo.getAbsolutePath();
                    CD.CargarConjTab(filename);
                    JOptionPane.showMessageDialog(null, "Fichero \""+archivo.getAbsoluteFile()+"\" cargado con exito.");
                }
                else JOptionPane.showMessageDialog(null, "El archivo seleccionado no es valido.");
            }
        }
    }//GEN-LAST:event_cargarConjActionPerformed

    private void analisis_rendimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analisis_rendimientoActionPerformed
        UsarAnalisis obj = new UsarAnalisis(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_analisis_rendimientoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_AdminAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_AdminAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_AdminAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_AdminAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_AdminAlgo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analisis_rendimiento;
    private javax.swing.JButton cargarConj;
    private javax.swing.JButton cliqueP;
    private javax.swing.JButton girvanN;
    private javax.swing.JButton guardarConj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton louvain;
    private javax.swing.JButton mostrarConj;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
