/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interficie;

import Dominio.ControladoraDominio;
import javax.swing.JOptionPane;


/**
 *
 * @author marc.mauri.ruiz
 */
public class UsarLouvain extends javax.swing.JFrame {

    ControladoraInterficie CD = new ControladoraInterficie();
    /**
     * Creates new form UsarLouvain
     */
    public UsarLouvain() {
        initComponents();
    }

    public UsarLouvain(ControladoraInterficie cd) {
        initComponents();
        CD = cd;
    }
    
    public void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,
                "¿Desea salir de la aplicación? Todos los cambios no guardados se perderán.",
                "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,
                null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        porcentaje = new javax.swing.JLabel();
        porcentaje_fijo = new javax.swing.JLabel();
        medidor = new javax.swing.JSlider();
        boton_calcular = new javax.swing.JButton();
        label_volver = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        mostrarConjuntos = new javax.swing.JButton();
        t_diferencia = new javax.swing.JLabel();
        lb_calculado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("YOUTUBE Mix: Uso del Louvain");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Algoritmo: Louvain");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Elije la dureza del cálculo:");

        porcentaje.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        porcentaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        porcentaje.setText("50");

        porcentaje_fijo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        porcentaje_fijo.setText("%");

        medidor.setMajorTickSpacing(25);
        medidor.setPaintLabels(true);
        medidor.setPaintTicks(true);
        medidor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                medidorStateChanged(evt);
            }
        });

        boton_calcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton_calcular.setText("Calcular");
        boton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_calcularActionPerformed(evt);
            }
        });

        label_volver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_volver.setText("Volver");
        label_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_volverActionPerformed(evt);
            }
        });

        menu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menu.setText("Menú");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        mostrarConjuntos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mostrarConjuntos.setText("Esperando cálculo");
        mostrarConjuntos.setEnabled(false);
        mostrarConjuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarConjuntosActionPerformed(evt);
            }
        });

        t_diferencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t_diferencia.setText("Tiempo de calculo");

        lb_calculado.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(medidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(porcentaje_fijo))
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label_volver)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lb_calculado))
                            .addComponent(t_diferencia)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(mostrarConjuntos)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(porcentaje_fijo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(medidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lb_calculado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarConjuntos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_diferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_volver)
                    .addComponent(menu))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medidorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_medidorStateChanged
        // TODO add your handling code here:
        this.porcentaje.setText(Integer.toString(this.medidor.getValue()));
    }//GEN-LAST:event_medidorStateChanged

    private void boton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_calcularActionPerformed
        // Se llama el calculo de los 3 algoritmos, para los tiempos y tal
        Long t_ini = new Long(System.currentTimeMillis());
        //String t_ini = time();
        int p = this.medidor.getValue();
        CD.calcLouvain(100-p);
        Long t_fin = new Long(System.currentTimeMillis());
        Long t_dif = new Long(t_fin - t_ini);
        if (t_dif > 59999) this.t_diferencia.setText("Ha tardado " + Long.toString(t_dif/1000/60) + " min y " + Long.toString(t_dif/1000%60) + "." + Long.toString((t_dif - 1000*(t_dif/1000/60*60 + t_dif/1000%60))/10) + " s");
        else if (t_dif > 999) this.t_diferencia.setText("Ha tardado " + Long.toString(t_dif/1000) + "." + Long.toString((t_dif%1000)/10) + " s");
        else this.t_diferencia.setText("Ha tardado " + Long.toString(t_fin-t_ini) + " ms");
        
        this.lb_calculado.setText("¡Calculado!");
        this.boton_calcular.setText("Recalcular");
        //this.boton_calcular.setEnabled(Boolean.FALSE);
        this.mostrarConjuntos.setText("Mostrar resultado");
        this.mostrarConjuntos.setEnabled(Boolean.TRUE);
    }//GEN-LAST:event_boton_calcularActionPerformed

    private void label_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_volverActionPerformed
        Menu_AdminAlgo obj = new Menu_AdminAlgo(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_label_volverActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        MenuPrincipal obj = new MenuPrincipal(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void mostrarConjuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarConjuntosActionPerformed
        MostrarConjuntos obj = new MostrarConjuntos(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_mostrarConjuntosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsarLouvain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsarLouvain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsarLouvain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsarLouvain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsarLouvain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton label_volver;
    private javax.swing.JLabel lb_calculado;
    private javax.swing.JSlider medidor;
    private javax.swing.JButton menu;
    private javax.swing.JButton mostrarConjuntos;
    private javax.swing.JLabel porcentaje;
    private javax.swing.JLabel porcentaje_fijo;
    private javax.swing.JLabel t_diferencia;
    // End of variables declaration//GEN-END:variables
}
