/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interficie;

import Dominio.ControladoraDominio;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author marc.mauri.ruiz
 */
public class UsarAnalisis extends javax.swing.JFrame {

    ControladoraInterficie CD = new ControladoraInterficie();
    /**
     * Creates new form UsarAnalisis
     */
    public UsarAnalisis() {
        initComponents();
    }

    public UsarAnalisis(ControladoraInterficie cd) {
        initComponents();
        CD = cd;
    }
    
    public void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,
                "¿Desea salir de la aplicación? Todos los cambios no guardados se perderán.",
                "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,
                null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        porcentaje = new javax.swing.JLabel();
        porcentaje_fijo = new javax.swing.JLabel();
        medidor = new javax.swing.JSlider();
        boton_calcular = new javax.swing.JButton();
        label_volver = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        t_clique = new javax.swing.JLabel();
        lb_calculado = new javax.swing.JLabel();
        descripcion_clique = new javax.swing.JLabel();
        descripcion_girvan = new javax.swing.JLabel();
        descripcion_louvain = new javax.swing.JLabel();
        t_girvan = new javax.swing.JLabel();
        t_louvain = new javax.swing.JLabel();
        conj_clique = new javax.swing.JLabel();
        conj_girvan = new javax.swing.JLabel();
        conj_louvain = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("YOUTUBE Mix: Análisis de rendimiento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Algoritmos: Análisis de rendimiento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Elije la dureza del cálculo:");

        porcentaje.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        porcentaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        porcentaje.setText("50");

        porcentaje_fijo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        porcentaje_fijo.setText("%");

        medidor.setMajorTickSpacing(25);
        medidor.setPaintLabels(true);
        medidor.setPaintTicks(true);
        medidor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                medidorStateChanged(evt);
            }
        });

        boton_calcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton_calcular.setText("Calcular");
        boton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_calcularActionPerformed(evt);
            }
        });

        label_volver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_volver.setText("Volver");
        label_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_volverActionPerformed(evt);
            }
        });

        menu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menu.setText("Menú");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        t_clique.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_clique.setText("Tiempo de calculo");

        lb_calculado.setText(" ");

        descripcion_clique.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descripcion_clique.setText("Clique Percolation:");

        descripcion_girvan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descripcion_girvan.setText("Girvan-Newman:");

        descripcion_louvain.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descripcion_louvain.setText("Louvain:");

        t_girvan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_girvan.setText("Tiempo de calculo");

        t_louvain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_louvain.setText("Tiempo de calculo");

        conj_clique.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conj_clique.setText("Nº Conjuntos");

        conj_girvan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conj_girvan.setText("Nº Conjuntos");

        conj_louvain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conj_louvain.setText("Nº Conjuntos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boton_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lb_calculado))
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(label_volver)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(medidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(porcentaje_fijo))))
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descripcion_girvan)
                            .addComponent(descripcion_clique)
                            .addComponent(descripcion_louvain))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_girvan)
                            .addComponent(t_louvain)
                            .addComponent(t_clique))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conj_girvan)
                            .addComponent(conj_louvain)
                            .addComponent(conj_clique))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(porcentaje_fijo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(medidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lb_calculado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcion_clique)
                            .addComponent(t_clique)
                            .addComponent(conj_clique))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcion_girvan)
                            .addComponent(t_girvan)
                            .addComponent(conj_girvan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcion_louvain)
                            .addComponent(t_louvain)))
                    .addComponent(conj_louvain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_volver)
                    .addComponent(menu))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medidorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_medidorStateChanged
        // TODO add your handling code here:
        this.porcentaje.setText(Integer.toString(this.medidor.getValue()));
    }//GEN-LAST:event_medidorStateChanged

    private void calcula_conjuntos(Integer id) {
        ArrayList<Object> tab = new ArrayList<>();
        tab = CD.ConvertirConjTab();
        Integer nConjuntos = new Integer((int) tab.get(0));
        if (id == 1) conj_clique.setText(Integer.toString(nConjuntos) + " conjuntos");
        else if (id == 2) conj_girvan.setText(Integer.toString(nConjuntos) + " conjuntos");
        else if (id == 3) conj_louvain.setText(Integer.toString(nConjuntos) + " conjuntos");
    }
    
    private void tiempo_clique() {
        Long t_ini = new Long(System.currentTimeMillis());
        int p = this.medidor.getValue();
        CD.calcClique(p);
        Long t_fin = new Long(System.currentTimeMillis());
        Long t_dif = new Long(t_fin - t_ini);
        if (t_dif > 59999) this.t_clique.setText("Ha tardado " + Long.toString(t_dif/1000/60) + " min y " + Long.toString(t_dif/1000%60) + "." + Long.toString((t_dif - 1000*(t_dif/1000/60*60 + t_dif/1000%60))/10) + " s.");
        else if (t_dif > 999) this.t_clique.setText("Ha tardado " + Long.toString(t_dif/1000) + "." + Long.toString((t_dif%1000)/10) + " s.");
        else this.t_clique.setText("Ha tardado " + Long.toString(t_fin-t_ini) + " ms.");
        
        calcula_conjuntos(1);
    }
    
    private void tiempo_girvan() {
        Long t_ini = new Long(System.currentTimeMillis());
        int p = this.medidor.getValue();
        CD.calcGirvan(p);
        Long t_fin = new Long(System.currentTimeMillis());
        Long t_dif = new Long(t_fin - t_ini);
        if (t_dif > 59999) this.t_girvan.setText("Ha tardado " + Long.toString(t_dif/1000/60) + " min y " + Long.toString(t_dif/1000%60) + "." + Long.toString((t_dif - 1000*(t_dif/1000/60*60 + t_dif/1000%60))/10) + " s.");
        else if (t_dif > 999) this.t_girvan.setText("Ha tardado " + Long.toString(t_dif/1000) + "." + Long.toString((t_dif%1000)/10) + " s.");
        else this.t_girvan.setText("Ha tardado " + Long.toString(t_fin-t_ini) + " ms.");
        
        calcula_conjuntos(2);
    }
    
    private void tiempo_louvain() {
        Long t_ini = new Long(System.currentTimeMillis());
        int p = this.medidor.getValue();
        CD.calcLouvain(100-p);
        Long t_fin = new Long(System.currentTimeMillis());
        Long t_dif = new Long(t_fin - t_ini);
        if (t_dif > 59999) this.t_louvain.setText("Ha tardado " + Long.toString(t_dif/1000/60) + " min y " + Long.toString(t_dif/1000%60) + "." + Long.toString((t_dif - 1000*(t_dif/1000/60*60 + t_dif/1000%60))/10) + " s.");
        else if (t_dif > 999) this.t_louvain.setText("Ha tardado " + Long.toString(t_dif/1000) + "." + Long.toString((t_dif%1000)/10) + " s.");
        else this.t_louvain.setText("Ha tardado " + Long.toString(t_fin-t_ini) + " ms.");
        calcula_conjuntos(3);
    }
    
    private void boton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_calcularActionPerformed
        // Se llama el calculo de los 3 algoritmos, para los tiempos y tal
        tiempo_clique();
        tiempo_girvan();
        tiempo_louvain();
        
        this.lb_calculado.setText("¡Calculado!");
        this.boton_calcular.setText("Recalcular");
    }//GEN-LAST:event_boton_calcularActionPerformed

    private void label_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_volverActionPerformed
        Menu_AdminAlgo obj = new Menu_AdminAlgo(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_label_volverActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        MenuPrincipal obj = new MenuPrincipal(CD);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsarAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsarAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsarAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsarAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsarAnalisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_calcular;
    private javax.swing.JLabel conj_clique;
    private javax.swing.JLabel conj_girvan;
    private javax.swing.JLabel conj_louvain;
    private javax.swing.JLabel descripcion_clique;
    private javax.swing.JLabel descripcion_girvan;
    private javax.swing.JLabel descripcion_louvain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton label_volver;
    private javax.swing.JLabel lb_calculado;
    private javax.swing.JSlider medidor;
    private javax.swing.JButton menu;
    private javax.swing.JLabel porcentaje;
    private javax.swing.JLabel porcentaje_fijo;
    private javax.swing.JLabel t_clique;
    private javax.swing.JLabel t_girvan;
    private javax.swing.JLabel t_louvain;
    // End of variables declaration//GEN-END:variables
}
